### ISSUE TITLE
add "type" property to requirements while parsing HTML

### ISSUE THREAD

**Issue by bugsalexander** [sandboxnu/graduatenu#21]
For different majors, there are different patterns of requirements. 

This issue proposes adding a "type" property to requirement objects, that would help specify the way that the requirement is meant to be completed. 

For example a requirement with the "take one of the following" patterns could have the type "one-of", or "or", or ...

Another pattern is the "range except". This requirement specifies classes in a range from some number to another number, except some other union of courses. This can be seen in the new CS major requirements (with concentrations):

Complete 8 credits of CS, CY, DS, or IS classes that are not already required. Choose courses within the following ranges: | 8
-- | --
CS 2500 or higher, except CS 5010 |  
CY 2000 or higher, except CY 4930 |  
DS 2000 or higher, except DS 4900 |  
IS 2000 or higher, except IS 4900

Adding this property to requirements is needed to suggest courses that could then fill those requirements, for the user to pick.

**Comment by JakeChvatal** [comment]
Would we still like to parse the required courses from the degree audit to retrieve the requirement objects? We should now have access to this information through the course catalog information. However, these courses will be able to hint at what majors/minors the student is pursuing, so they may be a useful form of validation or determining which degree requirements the student is using (i.e. new CS vs. old CS).

**Comment by jakeisnt** [comment]
hell yea
