### ISSUE TITLE
Revise "requirement" objects - HTML parser

### ISSUE THREAD

**Issue by bugsalexander** [sandboxnu/graduatenu#22]
This issue is for changing the "requirement" objects produced by the HTML parser to provide more information about their specifics.

See issue #18 "Fix class list representation" for details about requirement enumerations with multiple subjects.

See issue #21 "add "type" property to requirements while parsing html" for details about adding a new property "type" to further specify what KIND of requirement the object represents. 

This issue also covers additional requirement specifications that may be decided in the future, at the will of the authors.

**Comment by JakeChvatal** [comment]
We've moved away from the 'requirement' data definitions used in the past for the HTML parser.
