### ISSUE TITLE
Add ability to skip uploading degree audit.

### ISSUE THREAD

**Issue by bugsalexander** [sandboxnu/graduatenu#25]
For third-year students who've taken 16+ courses, it may be a lot easier to upload their degree audit, than manually enter in all the courses they've taken. However for a first-year, it would be super convenient to just select a major and enter the four or so courses they've taken. Additionally, this would provide an alternative to those with qualms against uploading their degree audit.

This would entail retrieving degree requirements from elsewhere, aka scraping the Northeastern catalog. For example, here are the [chemical engineering degree requirements](http://catalog.northeastern.edu/undergraduate/engineering/chemical/chemical-engineering-bsche/#programrequirementstext).

Once implemented, this could also serve to help SearchNEU. See the issue [here](https://github.com/ryanhugh/searchneu/issues/22).

Credit to Da-Jin: 
"I'm starting to wonder if it would be easier for some students to just select their major and then enter which classes they've taken, rather than do the entire degree audit process. Someone in their third year would enjoy the convenience of extracting all 16+ classes they taken out of the degree audit, but for someone in their first/second semester, wouldn't that be more work than it's worth?"

**Comment by JakeChvatal** [comment]
Done! We successfully scrape the Northeastern catalog for potential degree requirements in many cases. Though completing this feature still may be pending, our primary method of initializing a plan of study doesn't use the degree audit at all.
