### ISSUE TITLE
How to make this a full-stack application?

### ISSUE THREAD

**Issue by bugsalexander** [sandboxnu/graduatenu#6]
Structuring the code is dependent on the application framework. Research needed for choosing a fitting framework.

Should have a meeting to discuss (a) what framework to use and (b) working on the frontend.

**Comment by bugsalexander** [comment]
8 == more than a week.

**Comment by bugsalexander** [comment]
Was thinking about this the other day in terms of both testing and handling requests. Eventually, we'll have to run a server which will respond to requests with the appropriate information. How will we test this? Thinking about github's free CI/CD.

**Comment by JakeChvatal** [comment]
Our application is on its way to being built out! We currently have a hosted, usable prototype.
