### ISSUE TITLE
More prominent warning over degree audit

### ISSUE THREAD

**Issue by BrandonLim8890** [sandboxnu/graduatenu#661]
Although an important feature for our project, the "degree audit" sidebar can almost never be 100% accurate, and users should not be solely relying on us to validate whether they are able to graduate. As such, we should implement a better warning than what we have now. 

Current design:
<img width="584" alt="image" src="https://github.com/sandboxnu/graduatenu/assets/20124104/b6c00b5d-438a-4c35-b91f-e6a3d4b32bd7">

Ideas:
- Something "over" the sidebar that blurs the background, and requires the user to acknowledge that it may be unreliable before using the sidebar

Here are some other warnings that we should also consider. Don't be afraid to break this up into further issues to make it easier to manage once we identify exactly what we are going to be creating
1. A general warning over the app to basically say that we shouldn’t be the one source of truth for graduating and that we are just a tool to help
2. A warning over the sidebar stating again that its not fully accurate, even for majors that we have checked (we already have this but need to make it more prominent)
3. A warning over certain requirements within a major that we have hand-validated (we already have this but make it more prominent?)
4. A warning over beta majors
5. Maybe a warning when we show pre/co-reqs?

**Comment by AngelaZQ1** [comment]
@BrandonLim8890 Is this what you mean by number 3? This warning seems good enough to me <img width="491" alt="Screenshot 2024-02-08 at 4 11 03 PM" src="https://github.com/sandboxnu/graduatenu/assets/92692008/f72c377c-5592-4166-bf0c-0aa664fc914e">

Also something someone brought up in the designer meeting - We should probably limit our warnings to some degree because otherwise users might not even want to use our app

**Comment by elainedymin** [comment]
Hi here are designs for warnings:
1. A warning over the sidebar stating again that its not fully accurate, even for majors that we have checked -- [Here](https://www.figma.com/file/yUflVFVxjMynm7gGymLpQY/%F0%9F%8F%97-Current-Work?type=design&node-id=5741%3A34919&mode=design&t=q0ALpY9SOwwxBltM-1)

Will add more later. still need to get feedback from designer meeting on wed
