### ISSUE TITLE
Select Component Always Showing Black Text Even When Not Filled 

### ISSUE THREAD

**Issue by KobeZ123** [sandboxnu/graduatenu#696]
<img width="498" alt="Screenshot 2024-01-31 at 5 54 50 PM" src="https://github.com/sandboxnu/graduatenu/assets/57577392/97fcf4d1-8c7f-4fa5-a8bf-47e3466979e7">

In the current Select component, the "placeholder" text is black even though it would be more logical to have the text greyed out when it is not filled in. 

<img width="482" alt="Screenshot 2024-01-31 at 5 57 01 PM" src="https://github.com/sandboxnu/graduatenu/assets/57577392/16c890bb-06fb-4c1c-b750-b5f5015ec136">

The issue exists when the user has already selected an option. When they refocus on the element, they are able to start typing for a new search but it looks like the element has text filled in because the text color is black.

**Comment by AngelaZQ1** [comment]
@KobeZ123 can you clarify what you mean by that last part? The placeholder text should always be grey except when the user has typed something or selected an option from the dropdown, right?

**Comment by KobeZ123** [comment]
@AngelaZQ1 yup! actually that wording sounds a lot better than what i wrote for the issue

**Comment by KobeZ123** [comment]
@AngelaZQ1 if you are picking up this ticket, can you take a look at this branch https://github.com/sandboxnu/graduatenu/tree/select-text-color
i attempted to fix it by making the placeholder text gray when focused and black when unfocused. but there is an issue where after selecting an option from the dropdown, the select element is still focused and therefore showing grey.
<img width="469" alt="Screenshot 2024-02-01 at 6 47 03 PM" src="https://github.com/sandboxnu/graduatenu/assets/57577392/7b502023-2201-47f4-b877-b3657d93d7b9">
<img width="464" alt="Screenshot 2024-02-01 at 6 47 09 PM" src="https://github.com/sandboxnu/graduatenu/assets/57577392/c3f5c1d8-e103-4800-ae88-2ea8be8b28ec">
