### ISSUE TITLE
AP Transfer credits do not apply to the total credits completed

### ISSUE THREAD

**Issue by KobeZ123** [sandboxnu/graduatenu#743]
**Issue Summary:**
AP Transfer credits do not apply to the total credits completed

**Acceptance Criteria:** 
Implement changes so that AP Transfer credits are counted towards total credits completed

**Comment by hellolol2016** [comment]
Is there supposed to be a list of AP classes when you open up the add courses modal for the transfer courses section or are the students suppoesd to figure out themselves what their AP courses transfer to in the NEU course database? Right now, there is no list of AP classes in the add courses modal, but it should be a simple array.concat() into the list of NEU courses 

This is my popup for the transfer credit modal on the production graduatenu
![image](https://github.com/user-attachments/assets/a271c7d8-81b8-4ea9-ad26-d98c37f40923)

**Comment by hellolol2016** [comment]
Closed with https://github.com/sandboxnu/graduatenu/commit/e8ea7afe961008bd046f9afc2c05e0d821f6932c
