### ISSUE TITLE
Update the sorting of majors when creating a plan

### ISSUE THREAD

**Issue by KobeZ123** [sandboxnu/graduatenu#744]
**Issue Summary:**
When creating a new plan and selecting the major to base the plan off of, the majors should be listed in alphabetical order

It seems like the majors are currently being displayed in reverse alphabetical order, we can do alphabetical by default and search results in order if there is user input

**Acceptance Criteria:**
Update the sorting of the major selection for Add Plan modal ensuring it is alphabetical

**Comment by ulrichheringer** [comment]
Sent a PR fixing the issue!
