### ISSUE TITLE
[FEATURE]  Integration with SearchNEU Course Search

### ISSUE THREAD

**Issue by KobeZ123** [sandboxnu/graduatenu#750]
**Feature Summary:**
Button that links to SearchNEU's course page for the selected course 

Currently, the design is still TBD.

- Figure out how the SearchNEU query works for searching class results 
- Add a button that renders next to a course that links to Search and queries the class selected

Design:
https://www.figma.com/design/yUflVFVxjMynm7gGymLpQY/%F0%9F%8F%97-Current-Work?node-id=6230-47350&node-type=section&t=dMMXNFwqH2YEPn5r-0

Acceptance Criteria:
TBD

**Comment by hellolol2016** [comment]
I still think an iframe with details from search would be really cool, but that might be a little overkill. We got the job done.
