### ISSUE TITLE
[Feature] Sandbox Note Area on Sidebar 

### ISSUE THREAD

**Issue by KobeZ123** [sandboxnu/graduatenu#758]
**Feature Summary:**
Sandbox area for user notes

Implement a notes area allows the user to use as a notepad that is connected to their plan 

Design:
https://www.figma.com/design/yUflVFVxjMynm7gGymLpQY/%F0%9F%8F%97-Current-Work?node-id=6051-4784&t=JeZczBO4p0MJdSPD-4

Acceptance Criteria:

**Comment by hellolol2016** [comment]
- dont show when no plan selected
-

**Comment by Suraj-Ram** [comment]
- Only show the sandbox area when a plan is selected, since the notes should be tethered to a Plan
