### ISSUE TITLE
[BUG] Spacing for co-op education class tile is weird

### ISSUE THREAD

**Issue by KobeZ123** [sandboxnu/graduatenu#763]
**Issue Summary:**
spacing for co-op education class tile is weird

**Acceptance Criteria:**
- Figure out why this is the case and align if this needs to be fixed or if it is intentional

**Comment by hellolol2016** [comment]
are you referring to how it streches in the schedule? 
![image](https://github.com/user-attachments/assets/fbb3f757-80e4-4420-a918-c276d1da7c8b)
this is intentional in ScheduleCourse
`flex: scheduleCourse.classId === COOP_BLOCK.classId ? 1 : 0,`
